CREATE TABLE IF NOT EXISTS gyro_history (
    id SERIAL PRIMARY KEY,
    device_id INT REFERENCES devices(id) ON DELETE CASCADE,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    z DOUBLE PRECISION,
    timestamp TIMESTAMP DEFAULT NOW()
);
