-- devices
CREATE TABLE IF NOT EXISTS devices (
    id SERIAL PRIMARY KEY,
    owner_id INT REFERENCES users(id) ON DELETE CASCADE,
    device_name VARCHAR(100),
    device_color VARCHAR(50),
    pubnub_channel VARCHAR(100) UNIQUE NOT NULL,
    paired BOOLEAN DEFAULT FALSE,
    relay_channel1_enabled BOOLEAN DEFAULT TRUE,
    relay_channel1_override BOOLEAN DEFAULT FALSE,
    relay_channel1_alarm_type VARCHAR(20) DEFAULT 'continuous',
    relay_channel1_interval_sec INT DEFAULT 3,
    relay_channel1_trigger_mode VARCHAR(20) DEFAULT 'auto',
    relay_channel1_trigger_delay_sec INT,
    relay_channel2_enabled BOOLEAN DEFAULT TRUE,
    relay_channel2_override BOOLEAN DEFAULT FALSE,
    battery_saver_enabled BOOLEAN DEFAULT FALSE,
    battery_saver_threshold INT DEFAULT 20,
    gyroscope_enabled BOOLEAN DEFAULT TRUE,
    gps_enabled BOOLEAN DEFAULT TRUE,
    sms_alerts_enabled BOOLEAN DEFAULT TRUE,
    nfc_tag_id VARCHAR(100) UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
